import type { Metadata } from "next";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

import { UserProvider } from "../contexts/userContext";
import ToastProvider from "@/contexts/toastContext";
import AuthProvider from "@/contexts/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-full flex-col items-center justify-between">
          <UserProvider>
            <AuthProvider>
              <ToastProvider>
                <ToastContainer
                  closeOnClick
                  draggable
                  pauseOnFocusLoss
                  pauseOnHover
                  autoClose={3000}
                  hideProgressBar={true}
                  newestOnTop={false}
                  position="top-right"
                  theme="colored"
                />
                <Header />
                {children}
                <Footer />
              </ToastProvider>
            </AuthProvider>
          </UserProvider>
        </div>
      </body>
    </html>
  );
}
